import time

def fs(s):
    s(label='粉丝').click()
    time.sleep(2)
    s(className='Button').find_elements()[0].click()
    time.sleep(2)
    s(label='粉丝').click()
    time.sleep(2)
    s(label='新一').click()
    time.sleep(2)
    s(className='Button').find_elements()[0].click()
    time.sleep(2)
    s(label='新一').click()
    time.sleep(2)
    s(label='nav share').click()
    time.sleep(2)
    s(label='nav cross').click()
    time.sleep(1)
    s(className='Button').find_elements()[0].click()
    time.sleep(2)
    s(className='StaticText').find_elements()[1].click()
    time.sleep(2)
    s(label='取消').click()
    time.sleep(2)
    s(className='StaticText').find_elements()[1].click()
    time.sleep(2)
    s(label='确定').click()
    time.sleep(2)
    s(label='nav back').click()
    time.sleep(2)
    s(label='消息').click()
    time.sleep(2)
